<?php
include 'db_connect.php';

if (!isset($_GET['id'])) {
    die("Invalid request ID.");
}

$request_id = intval($_GET['id']);

$query = "SELECT vr.vaccine_request_id, vr.quantity, vr.request_date, 
                 v.vaccine_name, v.lot_number, v.expiry_date, v.description
          FROM vaccine_stock_requests vr
          JOIN vaccines v ON vr.vaccine_id = v.vaccine_id
          WHERE vr.request_id = ?";
$stmt = $conn->prepare($query);
$stmt->bind_param("i", $request_id);
$stmt->execute();
$result = $stmt->get_result();

if ($result->num_rows === 0) {
    die("Request not found.");
}

$row = $result->fetch_assoc();
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Print Vaccine Request</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; }
    .receipt {
      max-width: 600px;
      margin: auto;
      padding: 20px;
      border: 2px solid #333;
      border-radius: 10px;
      background: #fff;
    }
    h2, h3 { text-align: center; margin: 0; }
    .header { margin-bottom: 20px; }
    .info { margin: 15px 0; }
    .info label { font-weight: bold; display: inline-block; width: 150px; }
    .footer { margin-top: 30px; text-align: center; font-size: 14px; color: #555; }
    .btn-print {
      display: block;
      margin: 20px auto;
      padding: 10px 20px;
      background: #28a745;
      color: white;
      border: none;
      border-radius: 5px;
      font-size: 16px;
      cursor: pointer;
    }
    .btn-print:hover { background: #218838; }
  </style>
</head>
<body onload="window.print()">
  <div class="receipt">
    <div class="header">
      <h2>Barangay Health Station</h2>
      <h3>Vaccine Stock Request</h3>
      <hr>
    </div>

    <div class="info">
      <label>Request ID:</label> <?= $row['vaccine_request_id']; ?><br>
      <label>Vaccine Name:</label> <?= $row['vaccine_name']; ?><br>
      <label>Description:</label> <?= $row['description']; ?><br>
      <label>Lot Number:</label> <?= $row['lot_number']; ?><br>
      <label>Expiry Date:</label> <?= $row['expiry_date']; ?><br>
      <label>Quantity Requested:</label> <?= $row['quantity']; ?><br>
      <label>Request Date:</label> <?= $row['request_date']; ?><br>
    </div>

    <div class="footer">
      <p>Generated by Barangay Health Station Management System</p>
      <p>Date Printed: <?= date("Y-m-d H:i:s"); ?></p>
    </div>
  </div>
</body>
</html>

